version: '3.9'
services:
  caddy:
    image: 'caddy:latest'
    volumes:
      - ./provision/caddy/:/etc/caddy/
      #      - ./provision/caddy/tls:/etc/ssl/private
      - ./:/var/www/app
    ports:
      - '127.0.0.1:${APP_PORT:-80}:80'
  pgsql:
    image: 'postgres:16.2'
    restart: unless-stopped
    environment:
      POSTGRES_USER: '${DB_USERNAME:-root}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-root}'
      POSTGRES_DB: '${DB_DATABASE:-recipebox}'
    volumes:
      - pgsqlmount:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:${FORWARD_DB_PORT:-5432}:5432'
  php:
    build:
      context: .
      dockerfile: './provision/docker_php'
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
      - ./provision/imagick.xml:/etc/ImageMagick-6/policy.xml
  horizon:
    build:
      context: .
      dockerfile: './provision/docker_horizon'
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
    depends_on:
      - redis
  redis:
    image: 'redis:7.2.4-alpine'
    command: redis-server
    restart: unless-stopped
    ports:
      - '127.0.0.1:${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - redismount:/data
    sysctls:
      net.core.somaxconn: '2048'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      start_period: 0s
  mail:
    image: 'mailhog/mailhog:latest'
    ports:
      - '127.0.0.1:${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '127.0.0.1:${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
volumes:
  pgsqlmount:
  redismount:
